In [31]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib

In [32]:
df=pd.read_csv("d:\job_description.csv")

In [33]:
df.sample(10)

,Unnamed: 0,Category,Description,Benefits,Requirement,Requirements
238,238,Software Developer,Description\nWe are seeking a talented and exp...,NaN,NaN,Requirements\nBachelor’s degree in computer sc...
272,272,Software Developer,Description\nAbout SmartNews\nSmartNews is a l...,Benefits\nBenefits available at the SmartNews ...,NaN,Requirements\nMinimum requirements\n3 years of...
260,260,Software Developer,Description\nWe are looking for a Software Dev...,Benefits\nPrivate Health Insurance\nTraining &...,NaN,Requirements\nProven experience as a Software ...
250,250,Software Developer,Description\nABOUT US\nDo you have a passion f...,Benefits\nCommon App is a virtual first enviro...,NaN,Requirements\nQUALIFICATIONS\nThis role requir...
105,105,Data Scientist,Description\nData Science problems are everywh...,Benefits\nUnlimited PTO\nTraining & Developmen...,NaN,Requirements\nExtremely fluent in written and ...
7,7,Business Analyst,"Description\nIf you are a detail-oriented, cre...",Benefits\nWe have a simple motto when it comes...,Requirements\nWe're looking for someone with t...,NaN
209,209,HR,Description\nJob Brief:\nWe are seeking a high...,NaN,NaN,Requirements\nYour Qualifications:\nMaster’s d...
140,140,Data Scientist,Description\nAbout SmartNews\nSmartNews is a l...,Benefits\nBenefits available at the SmartNews ...,NaN,Requirements\nRequired experience:\nAdvanced d...
136,136,Data Scientist,Description\nArena’s Chief Technology Officer ...,NaN,NaN,Requirements\nThe individual will be able to w...
275,275,Software Developer,"Description\nHi, we’re Carbyne. We’re on a mis...",NaN,NaN,Requirements\nBachelor's degree in Software En...

In [34]:
df.isnull().sum()

Unnamed: 0        0
Category          0
Description       9
Benefits         53
Requirement     271
Requirements     64
dtype: int64

In [42]:
df["Required"]=df[["Requirement","Requirements"]].fillna("").agg(" ".join,axis=1).str.strip()

In [43]:
df

,Unnamed: 0,Category,Description,Benefits,Requirement,Requirements,Required
0,0,Business Analyst,Description\nJob Title: Junior Business Analys...,Benefits\nMethods is passionate about its peop...,Requirements\n• Confidence in communicating an...,NaN,Requirements\n• Confidence in communicating an...
1,1,Business Analyst,Description\nThe Business Analyst (BA) will ca...,Benefits\nA competitive base salary\nBonus sch...,Requirements\nYou have…\nA methodical approach...,NaN,Requirements\nYou have…\nA methodical approach...
2,2,Business Analyst,Description\nWe help our clients design and de...,Benefits\nWe have 2 promotion windows open eac...,"Requirements\nYou are open, curious, and excit...",NaN,"Requirements\nYou are open, curious, and excit..."
3,3,Business Analyst,Description\nFounded in 2015 and rapidly expan...,Benefits\nIn addition to a competitive package...,Requirements\nKey Responsibilities Include:\nP...,NaN,Requirements\nKey Responsibilities Include:\nP...
4,4,Business Analyst,Description\nWe are seeking a skilled Business...,Benefits\nFood Allowance\nGovernment Benefits\...,Requirements\nBachelor's Degree in management ...,NaN,Requirements\nBachelor's Degree in management ...
...,...,...,...,...,...,...,...
320,320,UI/UX,Description\nThe UX Designer will be focused o...,Benefits\nGovernment-mandated contributions: S...,NaN,Requirements\nMust Haves:\nNative or Fluent En...,Requirements\nMust Haves:\nNative or Fluent En...
321,321,UI/UX,Description\nWe are seeking a dynamic UI/UX de...,Benefits\nPrivate Health Insurance\nTraining &...,NaN,Requirements\nGather and evaluate user require...,Requirements\nGather and evaluate user require...
322,322,UI/UX,Description\nWe are looking for a UI/UX Design...,Benefits\nAttractive salaries\nHybrid work mod...,NaN,Requirements\nProven work experience as a UI/U...,Requirements\nProven work experience as a UI/U...
323,323,UI/UX,Description\nRemote – Full-Time\nClay is a glo...,Benefits\nFully remote work\nExcellent compens...,NaN,Requirements\nYou have 5+ years of digital des...,Requirements\nYou have 5+ years of digital des...
324,324,UI/UX,Description\nRemote – Full-Time\nClay is a glo...,Benefits\nFully remote work\nExcellent compens...,NaN,Requirements\nYou have 5+ years of digital des...,Requirements\nYou have 5+ years of digital des...

In [44]:
df=df.drop(columns=["Unnamed: 0","Benefits","Requirements","Requirement"])

In [45]:
df

,Category,Description,Required
0,Business Analyst,Description\nJob Title: Junior Business Analys...,Requirements\n• Confidence in communicating an...
1,Business Analyst,Description\nThe Business Analyst (BA) will ca...,Requirements\nYou have…\nA methodical approach...
2,Business Analyst,Description\nWe help our clients design and de...,"Requirements\nYou are open, curious, and excit..."
3,Business Analyst,Description\nFounded in 2015 and rapidly expan...,Requirements\nKey Responsibilities Include:\nP...
4,Business Analyst,Description\nWe are seeking a skilled Business...,Requirements\nBachelor's Degree in management ...
...,...,...,...
320,UI/UX,Description\nThe UX Designer will be focused o...,Requirements\nMust Haves:\nNative or Fluent En...
321,UI/UX,Description\nWe are seeking a dynamic UI/UX de...,Requirements\nGather and evaluate user require...
322,UI/UX,Description\nWe are looking for a UI/UX Design...,Requirements\nProven work experience as a UI/U...
323,UI/UX,Description\nRemote – Full-Time\nClay is a glo...,Requirements\nYou have 5+ years of digital des...
324,UI/UX,Description\nRemote – Full-Time\nClay is a glo...,Requirements\nYou have 5+ years of digital des...

In [46]:
df = df.dropna(subset=['Description'])

In [47]:
df

,Category,Description,Required
0,Business Analyst,Description\nJob Title: Junior Business Analys...,Requirements\n• Confidence in communicating an...
1,Business Analyst,Description\nThe Business Analyst (BA) will ca...,Requirements\nYou have…\nA methodical approach...
2,Business Analyst,Description\nWe help our clients design and de...,"Requirements\nYou are open, curious, and excit..."
3,Business Analyst,Description\nFounded in 2015 and rapidly expan...,Requirements\nKey Responsibilities Include:\nP...
4,Business Analyst,Description\nWe are seeking a skilled Business...,Requirements\nBachelor's Degree in management ...
...,...,...,...
320,UI/UX,Description\nThe UX Designer will be focused o...,Requirements\nMust Haves:\nNative or Fluent En...
321,UI/UX,Description\nWe are seeking a dynamic UI/UX de...,Requirements\nGather and evaluate user require...
322,UI/UX,Description\nWe are looking for a UI/UX Design...,Requirements\nProven work experience as a UI/U...
323,UI/UX,Description\nRemote – Full-Time\nClay is a glo...,Requirements\nYou have 5+ years of digital des...
324,UI/UX,Description\nRemote – Full-Time\nClay is a glo...,Requirements\nYou have 5+ years of digital des...

In [49]:
df.isnull().sum()

Category       0
Description    0
Required       0
dtype: int64

In [50]:
df["text"]=df["Description"]+" "+df["Required"]

C:\Users\hp\AppData\Local\Temp\ipykernel_2628\964742722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"]=df["Description"]+" "+df["Required"]

In [52]:
import re
import nltk
from nltk.corpus import stopwords   
from nltk.stem import PorterStemmer

In [53]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [54]:
ps=PorterStemmer()

In [55]:
def preprocess_text(text):
    text=text.lower()
    text=re.sub(r'[^a-zA-Z0-9\s]',' ',text)
    words=text.split()
    words=[ps.stem(word) for word in words if word not in stopwords.words('english')]
    return ' '.join(words)
df["processed_text"]=df["text"].apply(preprocess_text)

C:\Users\hp\AppData\Local\Temp\ipykernel_2628\537884960.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["processed_text"]=df["text"].apply(preprocess_text)

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer(max_features=5000)
X=tfidf.fit_transform(df["processed_text"]).toarray()

In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df["Category"])

In [58]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [59]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [60]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [61]:
y_pred = model.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.828125

In [63]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [64]:
nb_model = MultinomialNB()

svm_model = LinearSVC()

rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

In [65]:
nb_model.fit(X_train, y_train)

svm_model.fit(X_train, y_train)

rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

In [66]:
nb_pred = nb_model.predict(X_test)

svm_pred = svm_model.predict(X_test)

rf_pred = rf_model.predict(X_test)

In [67]:
print("Naive Bayes Accuracy:",
      accuracy_score(y_test, nb_pred))

print("Linear SVC Accuracy:",
      accuracy_score(y_test, svm_pred))

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_pred))

Naive Bayes Accuracy: 0.625
Linear SVC Accuracy: 0.859375
Random Forest Accuracy: 0.859375

In [68]:
from sklearn.metrics import classification_report

print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92        11
           1       1.00      0.33      0.50         9
           2       0.95      1.00      0.98        21
           3       0.67      1.00      0.80         4
           4       0.79      0.83      0.81        18
           5       1.00      1.00      1.00         1

    accuracy                           0.86        64
   macro avg       0.88      0.86      0.83        64
weighted avg       0.88      0.86      0.84        64

In [70]:
sample = """
Python, Machine Learning, Deep Learning,
TensorFlow, NLP, Data Analysis
"""

sample = preprocess_text(sample)

vector = tfidf.transform([sample])

prediction = svm_model.predict(vector)

print(le.inverse_transform(prediction))

['Data Scientist']

In [73]:
import joblib

joblib.dump(svm_model, "../saved_models/model.pkl")

joblib.dump(tfidf, "../saved_models/vectorizer.pkl")

joblib.dump(le, "../saved_models/encoder.pkl")

['../saved_models/encoder.pkl']